import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Both workers ship inside main.js, as source text. Obsidian's community
// catalogue and BRAT install exactly three files from a release — main.js,
// manifest.json and styles.css — so a worker shipped as its own file never
// reaches anyone who installs that way, and the PDF view has nothing to run.
// The main thread starts each worker from a same-origin blob of that text
// (see main.ts), which is also what desktop needs regardless: a Worker built
// from a plugin resource URL is cross-origin to the main window there.
//
// `import source from 'inline-worker:<name>'` bundles the named entry on its
// own and hands back its output as a string. Its inputs are reported as
// watch files, so `npm run dev` rebuilds main.js when a worker changes.
const INLINE_WORKERS = {
	// The pdf.js worker, run as a module Worker: bundled ESM.
	pdf: { entryPoint: 'node_modules/pdfjs-dist/build/pdf.worker.mjs', format: 'esm' },
	// pdf-lib's parse/mutate/save, off the main thread — see
	// src/pdf/annotationWriter.worker.ts for why. A classic script (iife):
	// blob-sourced code has no module URL to resolve imports against, and
	// bundling has already inlined everything, pdf-lib included.
	'annotation-writer': { entryPoint: 'src/pdf/annotationWriter.worker.ts', format: 'iife' },
};

const inlineWorkers = {
	name: 'inline-workers',
	setup(build) {
		build.onResolve({ filter: /^inline-worker:/ }, (args) => ({
			path: args.path.slice('inline-worker:'.length),
			namespace: 'inline-worker',
		}));
		build.onLoad({ filter: /.*/, namespace: 'inline-worker' }, async (args) => {
			const worker = INLINE_WORKERS[args.path];
			if (!worker) return { errors: [{ text: `Unknown inline worker "${args.path}"` }] };
			const result = await esbuild.build({
				entryPoints: [worker.entryPoint],
				bundle: true,
				format: worker.format,
				target: 'es2021',
				logLevel: 'silent',
				sourcemap: prod ? false : 'inline',
				treeShaking: true,
				minify: prod,
				write: false,
				metafile: true,
			});
			return {
				contents: result.outputFiles[0].text,
				loader: 'text',
				watchFiles: Object.keys(result.metafile.inputs),
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [inlineWorkers],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
