import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

// The pdf.js worker runs off-thread as a module Worker (loaded locally via
// DataAdapter.getResourcePath, never from a CDN — see hard requirements).
// It needs its own build: bundled ESM output, separate from main.js's cjs.
const workerContext = await esbuild.context({
	entryPoints: ['node_modules/pdfjs-dist/build/pdf.worker.mjs'],
	bundle: true,
	format: 'esm',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'pdf.worker.js',
	minify: prod,
});

// The annotation-writer worker (pdf-lib's parse/mutate/save, off the main
// thread — see src/pdf/annotationWriter.worker.ts for why).
//
// Built as a classic script (iife), not an ES module, and read as source
// text rather than loaded by URL: desktop Obsidian serves each vault's
// resource paths from their own origin (`app://<vaultId>`), distinct from
// the main window's (`app://obsidian.md`), and a Worker constructed from a
// script on that other origin throws SecurityError outright — confirmed on
// a real device, for a classic worker just as much as a module one, so it
// isn't a module-only restriction to dodge by changing format. The client
// builds the worker from a same-origin blob of this file's own source
// instead (see annotationWriterClient.ts). Blob-sourced code has no module
// URL to resolve imports against, and bundle:true has already inlined
// everything (pdf-lib included), so nothing here needs module semantics.
const annotationWriterWorkerContext = await esbuild.context({
	entryPoints: ['src/pdf/annotationWriter.worker.ts'],
	bundle: true,
	format: 'iife',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'annotation-writer.worker.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await workerContext.rebuild();
	await annotationWriterWorkerContext.rebuild();
	process.exit(0);
} else {
	await context.watch();
	await workerContext.watch();
	await annotationWriterWorkerContext.watch();
}
