import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { readFile } from 'node:fs/promises';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Both workers ship inside main.js, as source text. Obsidian's community
// catalogue and BRAT install exactly three files from a release — main.js,
// manifest.json and styles.css — so a worker shipped as its own file never
// reaches anyone who installs that way, and the PDF view has nothing to run.
// The main thread starts each worker from a same-origin blob of that text
// (see main.ts), which is also what desktop needs regardless: a Worker built
// from a plugin resource URL is cross-origin to the main window there.
//
// `import source from 'inline-worker:<name>'` bundles the named entry on its
// own and hands back its output as a string. Its inputs are reported as
// watch files, so `npm run dev` rebuilds main.js when a worker changes.
const INLINE_WORKERS = {
	// The pdf.js worker, run as a module Worker: bundled ESM.
	pdf: { entryPoint: 'node_modules/pdfjs-dist/build/pdf.worker.mjs', format: 'esm' },
	// pdf-lib's parse/mutate/save, off the main thread — see
	// src/pdf/annotationWriter.worker.ts for why. A classic script (iife):
	// blob-sourced code has no module URL to resolve imports against, and
	// bundling has already inlined everything, pdf-lib included.
	'annotation-writer': { entryPoint: 'src/pdf/annotationWriter.worker.ts', format: 'iife' },
};

// pdf.js carries the plugin's only dynamic code: a probe for whether
// `new Function` is allowed, and a fast path that compiles a PDF's PostScript
// (Type 4) functions into JavaScript when it is. Obsidian's plugin review
// flags any eval as code it cannot analyse, so both are taken out of the
// bundle rather than merely switched off at runtime (the loads also pass
// isEvalSupported: false). With the probe answering false, pdf.js runs those
// functions through its own interpreter, as it does wherever eval is blocked:
// the same output, a little slower on the few PDFs that use them.
//
// Each replacement must match exactly once, so a pdf.js upgrade that moves
// this code fails the build instead of quietly shipping eval again.
const PDFJS_EVAL_SITES = [
	{
		find: 'function isEvalSupported() {\n  try {\n    new Function("");\n    return true;\n  } catch {\n    return false;\n  }\n}',
		replace: 'function isEvalSupported() {\n  return false;\n}',
	},
	{
		find: '      if (compiled) {\n        return new Function("src", "srcOffset", "dest", "destOffset", compiled);\n      }\n',
		replace: '',
		workerOnly: true,
	},
];

const stripPdfjsEval = {
	name: 'strip-pdfjs-eval',
	setup(build) {
		build.onLoad({ filter: /pdfjs-dist[\\/]build[\\/]pdf(\.worker)?\.mjs$/ }, async (args) => {
			const isWorker = args.path.endsWith('pdf.worker.mjs');
			let source = (await readFile(args.path, 'utf8')).replace(/\r\n/g, '\n');
			for (const site of PDFJS_EVAL_SITES) {
				if (site.workerOnly && !isWorker) continue;
				const count = source.split(site.find).length - 1;
				if (count !== 1) {
					return { errors: [{ text: `strip-pdfjs-eval: expected one match in ${args.path}, found ${count}. Has pdf.js changed?` }] };
				}
				source = source.replace(site.find, site.replace);
			}
			if (/new Function\(|\beval\(/.test(source)) {
				return { errors: [{ text: `strip-pdfjs-eval: ${args.path} still contains dynamic code.` }] };
			}
			return { contents: source, loader: 'js' };
		});
	},
};

const inlineWorkers = {
	name: 'inline-workers',
	setup(build) {
		build.onResolve({ filter: /^inline-worker:/ }, (args) => ({
			path: args.path.slice('inline-worker:'.length),
			namespace: 'inline-worker',
		}));
		build.onLoad({ filter: /.*/, namespace: 'inline-worker' }, async (args) => {
			const worker = INLINE_WORKERS[args.path];
			if (!worker) return { errors: [{ text: `Unknown inline worker "${args.path}"` }] };
			const result = await esbuild.build({
				entryPoints: [worker.entryPoint],
				bundle: true,
				format: worker.format,
				target: 'es2021',
				logLevel: 'silent',
				sourcemap: prod ? false : 'inline',
				treeShaking: true,
				minify: prod,
				write: false,
				metafile: true,
				plugins: [stripPdfjsEval],
			});
			return {
				contents: result.outputFiles[0].text,
				loader: 'text',
				watchFiles: Object.keys(result.metafile.inputs),
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [inlineWorkers, stripPdfjsEval],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
